# Generated by Django 2.2.2 on 2019-07-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_image', models.ImageField(upload_to='')),
                ('campaign_title', models.CharField(max_length=100)),
                ('campaign_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming_Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_images', models.ImageField(upload_to='')),
                ('event_title', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_venue', models.CharField(max_length=20)),
            ],
        ),
    ]
