# Generated by Django 2.2.2 on 2019-07-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
