# Generated by Django 2.2.2 on 2019-07-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20190705_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='capaign_show',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
