# Generated by Django 2.2.2 on 2019-07-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20190715_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_text',
            field=models.TextField(default='True'),
        ),
    ]
