# Generated by Django 2.2.2 on 2019-07-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20190717_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='capaign_show',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='gallery_text',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_show',
            field=models.BooleanField(default='False'),
        ),
    ]
