# Generated by Django 2.2.2 on 2019-07-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20190718_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='upcoming_events',
            name='event_images',
            field=models.ImageField(upload_to='myedge/media'),
        ),
    ]
