# Generated by Django 2.2.2 on 2019-08-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_auto_20190808_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_date',
            field=models.DateField(default='19-08-08'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='award_time',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='upcoming_events',
            name='event_date',
            field=models.DateField(default='19-08-08'),
        ),
    ]
