# Generated by Django 2.2.2 on 2019-08-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_auto_20190808_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_Us',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='award_time',
        ),
        migrations.AddField(
            model_name='news',
            name='news_date',
            field=models.DateField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_date',
            field=models.DateField(blank=True),
        ),
    ]
