# Generated by Django 2.2.2 on 2019-08-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_auto_20190808_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='award_text',
        ),
        migrations.AddField(
            model_name='gallery',
            name='award_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
