# Generated by Django 2.2.2 on 2019-08-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_auto_20190808_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming_events',
            name='event_date',
            field=models.DateField(default='19-08-09'),
        ),
    ]
