# Generated by Django 2.2.2 on 2019-08-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_auto_20190809_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_date',
        ),
    ]
