# Generated by Django 2.2.2 on 2019-08-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_auto_20190809_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcoming_events',
            name='event_date',
        ),
    ]
