# Generated by Django 2.2.2 on 2019-08-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_remove_upcoming_events_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_show',
        ),
    ]
